### ISSUE TITLE
asyncio fail

### ISSUE THREAD

**Issue by lukeweston** [Kane610/axis#12]
On Python 3.7.3, when trying out your package I'm getting a problem with asyncio.
Please advise what environment / Python version / asyncio version you've used with this?
(And if there is any documentation, and where it exists?)

`Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
TypeError: __init__() takes 1 positional argument but 2 were given
`

**Comment by Kane610** [comment]
I'm using 3.7.3 as well

Best example is to look at the home assistant integration https://github.com/home-assistant/home-assistant/blob/eb912be47a2c9d032dbf9a84751c77d4896fa8b3/homeassistant/components/axis/device.py#L188

You can also look at the tests. They are not complete but I'm working on improving the tests

**Comment by Kane610** [comment]
Hey!

Updated the main function so you can get quite far with that now 👍 

https://github.com/Kane610/axis/blob/master/axis/__main__.py
