### ISSUE TITLE
any docs, quick getting started

### ISSUE THREAD

**Issue by dturton** [Kane610/axis#13]
Is there any documentation or a quick example of how to subscribe to an event stream?

**Comment by Kane610** [comment]
Sorry, no documentation. Closest is to look at the tests or the home assistant implementation right now.

Everything that is needed is referenced here https://github.com/home-assistant/home-assistant/blob/eb912be47a2c9d032dbf9a84751c77d4896fa8b3/homeassistant/components/axis/device.py#L68

Abbreviated you can do it with 
```
device = axis.AxisDevice(
        loop=hass.loop, host=config[CONF_HOST],
        username=config[CONF_USERNAME],
        password=config[CONF_PASSWORD],
        port=config[CONF_PORT], web_proto='http')
```

and 

`device.start()`

**Comment by dturton** [comment]
Thank you. Will give that a shot.

**Comment by Kane610** [comment]
Hey!

Updated the main function so you can get quite far with that now 👍 

https://github.com/Kane610/axis/blob/master/axis/__main__.py

**Comment by dturton** [comment]
Thank you!

**Comment by dturton** [comment]
Hi, I am getting an error -- Bad Request any idea what I am doing wrong?

`Received data ['RTSP/1.0 400 Bad Request', 'CSeq: 1', 'Server: GStreamer RTSP server', 'Date: Tue, 04 Jun 2019 12:09:48 GMT', ''] from 192.168.1.102
192.168.1.102 RTSP 400 Bad
RTSP session (192.168.1.102) state starting
DESCRIBE rtsp://192.168.1.102/axis-media/media.amp?video=0&audio=0&event=off RTSP/1.0
CSeq: 1
User-Agent: HASS Axis
Accept: application/sdp`

**Comment by Kane610** [comment]
Hmm. Could be that you do a rtsp request that doesn't want any content

**Comment by dturton** [comment]
```python
import asyncio
import axis
import logging

from axis import AxisDevice


async def main():
    loop = asyncio.get_event_loop()
    device = AxisDevice(
        loop=loop, host="192.168.1.102", username="user",
        password="pass", port=80)

    device.start()

    try:
        while True:
            await asyncio.sleep(1)

    except KeyboardInterrupt:
        pass

    finally:
        device.stop()


logging.basicConfig(format='%(message)s', level=logging.DEBUG)
asyncio.run(main())
```

**Comment by Kane610** [comment]
Sorry, I had removed one line for some reason... It is fixed now

**Comment by wiseman** [comment]
Do you have any examples of moving (panning or tilting) the camera?

**Comment by Kane610** [comment]
No. There is no ptz support in this library yet

**Comment by Kane610** [comment]
Just an FYI Im gonna implement PTZ support shortly
