### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by alexg-axis** [Kane610/axis#149]
I saw in a thread somewhere that you may be planning to do some work on this plugin in the near future. It would be great to have HTTPS support and the ability to specify the certificate to expect from the camera, to support self-signed certificates without messing with the certificates trusted by the host / client.

**Comment by Kane610** [comment]
Yes this is on my list of things to do. I'm reworking the unifi integration right now and once I'm done with that I will drt my eyes to improving this integration as well.

**Comment by terminalcowboy** [comment]
Just wanted to come here and vote for https. I run a bunch of axis cameras configured by camera station and the home assistant integration wont configure them with the correct passwords. I am guessing due to lack of ssl. Is there a way to connect to the axis camera station server instead of every individual camera or are there benefits to interfacing to the cameras directly? Anyway, thanks

**Comment by Kane610** [comment]
I think this will be on the top of my list to fix once the refactoring is complete, there is no specific reason for not supporting HTTPS only that it wasn't as important back in the days when the integration was created.

I don't have an ACS instance and I don't know what kind of API ACS provides. Right now based on what I know I would say no.

**Comment by Kane610** [comment]
HTTPS support has been added with HASS 2024.4.0, beta is out tonight. Feedback is appreciated!

**Comment by terminalcowboy** [comment]
Awesome thanks for doing this! I patched everything to the latest and the
HTTPS does seem to be working. The only thing I am noticing now is that
there is no thumbnail or preview on the dashboard or entity with my newer
cameras. I have a very old M5014 that works with no SSL and it has always
displayed its image. I am new to home assistant though so could be just me
missing something. It works though Yay, if i click on either of these it
loads the video player and the video populates after a few seconds, with
audio.
[image: image.png]

**Comment by Kane610** [comment]
> Awesome thanks for doing this! I patched everything to the latest and the HTTPS does seem to be working. The only thing I am noticing now is that there is no thumbnail or preview on the dashboard or entity with my newer cameras. I have a very old M5014 that works with no SSL and it has always displayed its image. I am new to home assistant though so could be just me missing something. It works though Yay, if i click on either of these it loads the video player and the video populates after a few seconds, with audio.

Yes I missed the camera platform. Fix is up https://github.com/home-assistant/core/pull/114886 for 2024.4.1
