### ISSUE TITLE
Option to choose stream profile

### ISSUE THREAD

**Issue by svaneepoel** [Kane610/axis#17]
HI Kane,

As discussed yesterday in the HA Github, could you please create an option to choose a stream profile in the Axis HA integration?

When I open multiple camera views (like mobile phone app, lovelace dashboard, Axis recorder), and they all use different profiles, I often get no livestream and the warning "Too many viewers".

More info about this can be found here:
https://www.axis.com/support/faq/FAQ115847
https://www.axis.com/files/whitepaper/White_paper_buffer_limitation.pdf

It looks like they suggest to use the same stream profile on multiple devices to prevent this problem.

Thanks in advance for looking at this and for all the great work!

**Comment by Kane610** [comment]
Great suggestion! I have a pile of things for the Axis integration which I will start looking at when I'm done with fixing the unifi integration

**Comment by Kane610** [comment]
Fixed and supported in HASS, closing this issue.
