### ISSUE TITLE
file conflicts with aiounify package?

### ISSUE THREAD

**Issue by onkelbeh** [Kane610/axis#378]
somehow axis-50 claims a filename which conflicts with aiounify, perhaps a mistake?

```
 * >>> Extracting dev-python/axis-50
 *
 * Detected file collision(s):
 *
 * 	/usr/lib/python-exec/python3.11/aiounifi
 * 	/usr/lib/python-exec/python3.12/aiounifi
 * 	/usr/bin/aiounifi
 *
 * Searching all installed packages for file collisions...
 *
 * Press Ctrl-C to Stop
 *
 * dev-python/aiounifi-72:0::HomeAssistantRepository
 * 	/usr/bin/aiounifi
 * 	/usr/lib/python-exec/python3.11/aiounifi
 * 	/usr/lib/python-exec/python3.12/aiounifi
 *
 * Package 'dev-python/axis-50' NOT merged due to file collisions.
```

https://github.com/Kane610/axis/blame/1ca8ea0128d0dc6826a2fae0a4637b00c19ff94c/pyproject.toml#L57

**Comment by Kane610** [comment]
Ive never had that issue myself so not sure why you get it, seeing as you have both python 3.11 and 3.12 listed you don't run in a virtual environment?

**Comment by Kane610** [comment]
This is out with axis v54 and merged to hass dev so shouldn't affect you anymore
