### ISSUE TITLE
Delay in Home Assistant live view

### ISSUE THREAD

**Issue by svaneepoel** [Kane610/axis#38]
Hi Kane,

I don't know if you can help me with this, but I've the problem that my live view in HA always have a delay of +- 10 seconds.
If this with both my Axis cameras, and it has always been like this.

Do you have any idea about how to make the delay shorter?

**Comment by Kane610** [comment]
What device is it you've got issues with? Sounds like you only get mjpeg stream. If the device supports h264 the latency is usually much lower

**Comment by svaneepoel** [comment]
Hi,

Thank you for the fast response! My cameras are:

- AXIS M2026-LE Mk II
- AXIS M3106-LVE Mk II 

They both support h264. I only added them using the integration in Home Assistant, so I didn't had to choose between mjpeg and h264 I think?

I'm also reading that the frame rate could be the problem? Here you can see my stream settings of the cameras:
[](https://i.imgur.com/KzwPZPw.png)
[](https://i.imgur.com/3sqxCX5.png)

**Comment by Kane610** [comment]
You can try selecting a different stream profile in the integration options. It could be that your host running hass is to slow

**Comment by svaneepoel** [comment]
I tried to do that, but it always give me a blank white live view in HA.

**Comment by svaneepoel** [comment]
fyi, I tried to change some more settings, and disabling dynamic GOP en dynamic FPS, it reduced the delay to 3 seconds!
The only 'problem' I have is that I can't use streaming profiles. When I try that, it keeps giving me a blank live view. It works perfect without streaming profile.

**Comment by Kane610** [comment]
Can you enable debug per integration documentation and share logs?
