### ISSUE TITLE
Request: option to allow stream to be configurable

### ISSUE THREAD

**Issue by WhistleMaster** [Kane610/axis#49]
Thanks for the great work on this component !

It would be great to get an option to allow stream to be configurable. I have an AXIS M3058, and the default image with the component is the 360° fisheye view. It would be great to be able to select, as an example, the quad-view.

Thanks !

**Comment by Kane610** [comment]
Awesome!

Just a thought: stream profiles doesn't solve this? https://github.com/Kane610/axis/blob/master/axis/stream_profiles.py

**Comment by WhistleMaster** [comment]
Unfortunately, no, you can't select a "view" for a profile. It seems that it's only for parameters such as resolutions, etc.

I can use different URLs, such as `http://<AXIS_IP>/axis-cgi/jpg/image.cgi?camera={1-12}` to get a still image, or `rtsp://<AXIS_IP>/axis-media/media.amp?videocodec=h264&camera={1-12}` for streaming.

**Comment by WhistleMaster** [comment]
Just figured out something this morning that I can't explain actually... If I setup both the ONVIF and the AXIS integration for my camera, I get all the different profiles with each view and also the different sensors BUT if I setup each integration separately, either I get the different profiles with each views but not sensors _vice-versa_.

Strange thing is that I can't select any profile with the AXIS integration:
<img width="431" alt="Screenshot 2020-12-24 at 14 07 31" src="https://user-images.githubusercontent.com/1544568/103090786-668f4680-45f2-11eb-9581-17400d04a10e.png">

**Comment by Kane610** [comment]
I will look at this soon. The two integrations shouldn't affect each other

**Comment by Kane610** [comment]
@WhistleMaster could you share logs of this behavior?

**Comment by Kane610** [comment]
Have you configured stream profiles on the camera? I dont think there are any automatically created profiles but you have to do it yourself

**Comment by WhistleMaster** [comment]
Yes there are already thereon the camera and I can get them with the ONVIF integration. Which logs would you like ?

**Comment by Kane610** [comment]
So you mean you don't get the stream profiles from the camera with the axis integration? Are you perhaps using too low level of credentials?

Enable debug logging for the axis integration and share what pops out of it :)

**Comment by WhistleMaster** [comment]
Indeed. I've tried with the root user with the AXIS integration but I don't get any stream profiles either. I've created a ONVIF user in "administrator" user group, but it doesn't work with the AXIS integration (I cannot log in from the integration) but this user does work with the ONVIF integration and I get the stream profiles.

I will enable debug logging and send the logs :)

**Comment by WhistleMaster** [comment]
And here are the logs:
[ha_logs.txt](https://github.com/Kane610/axis/files/5760044/ha_logs.txt)

**Comment by Kane610** [comment]
According to the logs there are no configured stream profiles. And I'm working on adding proper view area support

**Comment by Kane610** [comment]
How are the different views for your 360 device presented? How do you know that you get a view which is not the 360° view?

**Comment by Kane610** [comment]
Parts of it is solved, but not yet in home assistant

**Comment by WhistleMaster** [comment]
> According to the logs there are no configured stream profiles. And I'm working on adding proper view area support

Well, the profiles are defined in the OVNIF section of the camera ("ONVIF media profiles"), that's maybe why I can see it with the OVNIF integration but not with the AXIS one. I don't have stream profiles defined in the "Stream profiles" section.

<img width="321" alt="Screenshot 2021-01-05 at 12 33 27" src="https://user-images.githubusercontent.com/1544568/103641609-506a7a00-4f52-11eb-8e63-f8f588efa210.png">
<img width="335" alt="Screenshot 2021-01-05 at 12 33 41" src="https://user-images.githubusercontent.com/1544568/103641613-51031080-4f52-11eb-8320-1d807395b6e0.png">

> How are the different views for your 360 device presented? How do you know that you get a view which is not the 360° view? 
They are available with the "ONVIF media profiles" but not with the "Stream profiles". I have to use an OVNIF user to get them with the ONVIF integration.

**Comment by Kane610** [comment]
Ok, well I'm not utilizing any onvif functionality. Its all Vapix APIs I call

**Comment by WhistleMaster** [comment]
That’s why then, so the only way to get the different views other than the 360 one is to use the ONVIF profiles and the ONVIF integration because the standard AXIS stream profiles through vapix calls don’t propose this option to choose the view. 

I guess we can close this issue. Thanks for your help !

**Comment by Kane610** [comment]
Isn't it worth investigating more?

**Comment by WhistleMaster** [comment]
You tell me :)

As I see it, the only way would be to include some ONVIF functions in your AXIS integration to include the profiles but that would require two different users, one for the AXIS integration and one for the ONVIF.

**Comment by WhistleMaster** [comment]
I don't know if that could be of any help, but Synology Surveillance Station allows to select a "Video Channel" and it is not using ONVIF.

<img width="398" alt="Screenshot 2021-01-09 at 08 19 08" src="https://user-images.githubusercontent.com/1544568/104085939-9033a900-5253-11eb-8332-da5117be87d3.png">

**Comment by Kane610** [comment]
I think those are view areas. I have that implemented. Just need to verify everything :)

**Comment by Kane610** [comment]
I think I found it, it is the root.Image parameters in param.cgi

**Comment by Kane610** [comment]
I've done something, try it out in beta shortly!

**Comment by Kane610** [comment]
Haven't heard anything and functionality is available, closing this. Feedback would be appreciated.

**Comment by WhistleMaster** [comment]
I've just updated HA this morning and tried the new AXIS integration and... it's working perfectly fine ! That's great, I can select the view now, thanks for the great work !

**Comment by Kane610** [comment]
Thanks for the feedback! Happy i could solve it 😃
