### ISSUE TITLE
TLS verification is not properly disabled

### ISSUE THREAD

**Issue by ThiefMaster** [Kane610/axis#5]
https://github.com/Kane610/axis/blob/master/axis/configuration.py#L25

The `Session` attribute is named `verify`, not `verify_ssl`, so setting it doesn't do anything.
Also, it should be set regardless of `web_proto` since the camera might redirect from http to https depending on its configuration.

**Comment by Kane610** [comment]
Thanks! I will look into this.

**Comment by Kane610** [comment]
Fixed. Thanks for reporting.
